name: Psalm Scan


on:
    push:
    pull_request:
    workflow_dispatch:


jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
          - name: Check out code
            uses: actions/checkout@v2


          - name: Scan code with Psalm
            uses: docker://ghcr.io/psalm/psalm-security-scan
            env:
                COMPOSER_AUTH: '{"github-oauth":{"github":"${{ secrets.ORG_GITHUB_TOKEN }}"}}'
                GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN}}


          - name: Upload results to Github
            uses: github/codeql-action/upload-sarif@v1
            with:
                sarif_file: results.sarif

