name: Test Workflow

on:
    push:
    workflow_dispatch:


jobs:
    TestFlow:
        name: Hede
        runs-on: ubuntu-latest
        steps:
            - name: Perform test
              uses: actions/checkout@v1


            - name: Test with Hede
              #uses: docker://shiftleft/scan-slim:latest
              #uses: docker://shiftleft/sast-scan:latest
              #uses: ShiftLeftSecurity/sast-scan@master
              uses: docker://nsyilmaz/git-research:latest
